const nycData = {
    artists: [
        {
            name: "Frank Sinatra", id: "sinatra", icon: "🎩",
            songs: [
                {
                    title: "My Way", id: "my_way",
                    lyrics: [
                        { eng: "And now, the end is near", esp: "Y ahora, el final está cerca", pro: "an nau, di end is niar" },
                        { eng: "And so I face the final curtain", esp: "Y así enfrento el telón final", pro: "an sou ai feis de fainal kerten" },
                        { eng: "My friend, I'll say it clear", esp: "Mi amigo, lo diré claramente", pro: "mai frend, ail sei it kliar" },
                        { eng: "I'll state my case, of which I'm certain", esp: "Expondré mi caso, del cual estoy seguro", pro: "ail steit mai keis, ov uich aim serten" },
                        { eng: "I've lived a life that's full", esp: "He vivido una vida plena", pro: "aiv livd a laif dats ful" },
                        { eng: "I travelled each and every highway", esp: "Viajé por cada una de las carreteras", pro: "ai traveld ich an evri jai-uei" },
                        { eng: "And more, much more than this", esp: "Y más, mucho más que esto", pro: "an mor, mach mor dan dis" },
                        { eng: "I did it my way", esp: "Lo hice a mi manera", pro: "ai did it mai uei" },
                        { eng: "Regrets, I've had a few", esp: "Arrepentimientos, tuve algunos", pro: "rigrets, aiv jad a fiu" },
                        { eng: "But then again, too few to mention", esp: "Pero de nuevo, muy pocos para mencionar", pro: "bat den aguen, tu fiu tu menshon" },
                        { eng: "I did what I had to do", esp: "Hice lo que tenía que hacer", pro: "ai did uat ai jad tu du" },
                        { eng: "And saw it through without exemption", esp: "Y lo logré sin excepciones", pro: "an so it thru uid-aut eksempshon" },
                        { eng: "I planned each charted course", esp: "Planifiqué cada curso trazado", pro: "ai pland ich charted kors" },
                        { eng: "Each careful step along the byway", esp: "Cada paso cuidadoso por el camino", pro: "ich kerful estep a-lon de bai-uei" },
                        { eng: "And more, much more than this", esp: "Y más, mucho más que esto", pro: "an mor, mach mor dan dis" },
                        { eng: "I did it my way", esp: "Lo hice a mi manera", pro: "ai did it mai uei" },
                        { eng: "Yes, there were times, I'm sure you knew", esp: "Sí, hubo momentos, seguro lo sabías", pro: "ies, der uer taims, aim shur yu niu" },
                        { eng: "When I bit off more than I could chew", esp: "Cuando mordí más de lo que podía masticar", pro: "uen ai bit of mor dan ai kul chu" },
                        { eng: "But through it all, when there was doubt", esp: "Pero en todo, cuando hubo duda", pro: "bat thru it ol, uen der uas daut" },
                        { eng: "I ate it up and spit it out", esp: "Lo engullí y lo escupí", pro: "ai eit it ap an espit it aut" },
                        { eng: "I faced it all and I stood tall", esp: "Lo enfrenté todo y me mantuve firme", pro: "ai feist it ol an ai estud tol" },
                        { eng: "And did it my way", esp: "Lo hice a mi manera", pro: "ai did it mai uei" },
                        { eng: "I've loved, I've laughed and cried", esp: "He amado, reído y llorado", pro: "aiv lavd, aiv laft an kraid" },
                        { eng: "I've had my fill, my share of losing", esp: "Tuve mi parte de pérdida", pro: "aiv jad mai fill, mai sher ov lusin" },
                        { eng: "And now, as tears subside", esp: "Y ahora, al calmarse las lágrimas", pro: "an nau, as tiars sabsid" },
                        { eng: "I find it all so amusing", esp: "Lo encuentro muy divertido", pro: "ai faind it ol sou amiusing" },
                        { eng: "To think I did all that", esp: "Pensar que hice todo eso", pro: "tu dink ai did ol dat" },
                        { eng: "And may I say, not in a shy way", esp: "Y no de manera tímida", pro: "an mei ai sei, not in a shai uei" },
                        { eng: "Oh, no, oh, no, not me", esp: "Oh no, yo no", pro: "ou nou, ou nou, not mi" },
                        { eng: "I did it my way", esp: "Lo hice a mi manera", pro: "ai did it mai uei" },
                        { eng: "For what is a man, what has he got?", esp: "¿Qué es un hombre? ¿qué tiene?", pro: "for uat is a man, uat jas ji gat" },
                        { eng: "If not himself, then he has naught", esp: "Si no se tiene a sí mismo, no tiene nada", pro: "if not jim-self, den ji jas not" },
                        { eng: "To say the things he truly feels", esp: "Decir lo que realmente siente", pro: "tu sei de dings ji truli fils" },
                        { eng: "And not the words of one who kneels", esp: "Y no las palabras de uno que se arrodilla", pro: "an not de uords ov uan ju nils" },
                        { eng: "The record shows I took the blows", esp: "El historial muestra que acepté los golpes", pro: "de rekord shous ai tuk de blous" },
                        { eng: "And did it my way", esp: "Lo hice a mi manera", pro: "ai did it mai uei" },
                        { eng: "Yes, it was my way", esp: "Sí, fue a mi manera", pro: "ies, it uas mai uei" }
                    ]
                },
                {
                    title: "New York, New York", id: "ny_ny",
                    lyrics: [
                        { eng: "Start spreading the news", esp: "Empiecen a difundir las noticias", pro: "stard espredin de nius" },
                        { eng: "I'm leaving today", esp: "Me voy hoy mismo", pro: "aim livin tudei" },
                        { eng: "I want to be part of it", esp: "Quiero ser parte", pro: "ai uant tu bi pard ov it" },
                        { eng: "New York, New York", esp: "Nueva York", pro: "nu iork, nu iork" },
                        { eng: "These vagabond shoes", esp: "Estos zapatos de vagabundo", pro: "dis vagabond shus" },
                        { eng: "Are longing to stray", esp: "Desean vagar", pro: "ar lon-guin tu estrei" },
                        { eng: "Right through the very heart of it", esp: "Por el corazón de ella", pro: "rait thru de veri jart ov it" },
                        { eng: "New York, New York", esp: "Nueva York", pro: "nu iork, nu iork" },
                        { eng: "I wanna wake up in that city", esp: "Quiero despertar en esa ciudad", pro: "ai uana ueik ap in dat siti" },
                        { eng: "That doesn't sleep", esp: "Que no duerme", pro: "dat dasent eslip" },
                        { eng: "And find I'm king of the hill", esp: "Ser el rey", pro: "an faind aim kin ov de jil" },
                        { eng: "Top of the heap", esp: "En la cima", pro: "top ov de jip" },
                        { eng: "These little town blues", esp: "Penas de pueblo", pro: "dis litel taun blus" },
                        { eng: "Are melting away", esp: "Se esfuman", pro: "ar meltin a-uei" },
                        { eng: "I'll make a brand-new start of it", esp: "Un nuevo comienzo", pro: "ail meik a brand-niu estart" },
                        { eng: "In old New York", esp: "En la vieja NY", pro: "in ould nu iork" },
                        { eng: "If I can make it there", esp: "Si lo logro allá", pro: "if ai kan meik it der" },
                        { eng: "I'll make it anywhere", esp: "Lo lograré en cualquier parte", pro: "ail meik it eni-uer" },
                        { eng: "It's up to you", esp: "Depende de ti", pro: "its ap tu yu" },
                        { eng: "New York, New York", esp: "Nueva York", pro: "nu iork, nu iork" },
                        { eng: "New York, New York", esp: "Nueva York", pro: "nu iork, nu iork" },
                        { eng: "I want to wake up", esp: "Despertar", pro: "ai uant tu ueik ap" },
                        { eng: "In a city that never sleeps", esp: "Ciudad que nunca duerme", pro: "in a siti dat never eslips" },
                        { eng: "And find I'm a number one", esp: "Ser el número uno", pro: "an faind aim a namber uan" },
                        { eng: "Top of the list", esp: "Primero en la lista", pro: "top ov de list" },
                        { eng: "King of the hill", esp: "Rey de la colina", pro: "kin ov de jil" },
                        { eng: "A number one", esp: "Número uno", pro: "a namber uan" },
                        { eng: "These little town blues", esp: "Penas de pueblo", pro: "dis litel taun blus" },
                        { eng: "Are melting away", esp: "Se esfuman", pro: "ar meltin a-uei" },
                        { eng: "I'm gonna make a brand-new start of it", esp: "Nuevo comienzo", pro: "aim gana meik a brand-niu estart" },
                        { eng: "In old New York", esp: "En la vieja NY", pro: "in ould nu iork" },
                        { eng: "And", esp: "Y", pro: "and" },
                        { eng: "If I can make it there", esp: "Si lo logro allá", pro: "if ai kan meik it der" },
                        { eng: "You know I'm gonna make it anywhere", esp: "Sabes que lo lograré en cualquier parte", pro: "yu nou aim gana meik it eni-uer" },
                        { eng: "It's up to you", esp: "Depende de ti", pro: "its ap tu yu" },
                        { eng: "New York, New York!", esp: "¡Nueva York!", pro: "nu iork, nu iork!" },
                        { eng: "New York!", esp: "¡Nueva York!", pro: "nu iork!" }
                    ]
                }
            ]
        },
        {
            name: "Harry Styles", id: "harry_styles", icon: "🕺",
            songs: [
                {
                    title: "Sign of the Times", id: "sign_times",
                    lyrics: [
                        { eng: "Just stop your crying, it's a sign of the times", esp: "Deja de llorar, señal de los tiempos", pro: "yost estop iur krain, its a sain ov de taims" },
                        { eng: "Welcome to the final show", esp: "Bienvenidos al show final", pro: "uel-kam tu de fainal shou" },
                        { eng: "Hope you're wearing your best clothes", esp: "Usa tu mejor ropa", pro: "joup iur uerin iur best klous" },
                        { eng: "You can't bribe the door on your way to the sky", esp: "No puedes sobornar la puerta", pro: "yu kant braib de dor on iur uei tu de skai" },
                        { eng: "You look pretty good down here", esp: "Te ves bien aquí abajo", pro: "yu luk priti gud daun jiar" },
                        { eng: "But you ain't really good", esp: "Pero no eres bueno", pro: "bat yu eint rili gud" },
                        { eng: "We never learn, we've been here before", esp: "Nunca aprendemos", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "¿Por qué siempre estamos atrapados huyendo de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "The bullets?", esp: "¿Las balas?", pro: "de bulets" },
                        { eng: "The bullets?", esp: "¿Las balas?", pro: "de bulets" },
                        { eng: "We never learn, we've been here before", esp: "Ya estuvimos aquí antes", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "¿Por qué siempre huimos de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "Your bullets?", esp: "¿Tus balas?", pro: "iur bulets" },
                        { eng: "A bullet?", esp: "¿Una bala?", pro: "a bulet" },
                        { eng: "Just stop your crying, it's a sign of the times", esp: "Deja de llorar, es la señal", pro: "yost estop iur krain, its a sain ov de taims" },
                        { eng: "We gotta get away from here", esp: "Hay que irnos de aquí", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "We gotta get away from here", esp: "Hay que irnos de aquí", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "Just stop your crying, it'll be alright", esp: "Todo estará bien", pro: "yost estop iur krain, it-l bi ol-rait" },
                        { eng: "They told me that the end is near", esp: "Me dijeron que el fin está cerca", pro: "dei told mi dat di end is niar" },
                        { eng: "We gotta get away from here", esp: "Hay que salir de aquí", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "Just stop your crying, have the time of your life", esp: "Pásalo increíble", pro: "yost estop iur krain, jav de taim ov iur laif" },
                        { eng: "Breaking through the atmosphere", esp: "Atravesando la atmósfera", pro: "breikin thru di atmos-fiar" },
                        { eng: "And things are pretty good from here", esp: "Las cosas se ven bien aquí", pro: "an dins ar priti gud fram jiar" },
                        { eng: "Remember everything will be alright", esp: "Recuerda, todo estará bien", pro: "rimember evridin uil bi ol-rait" },
                        { eng: "We can meet again somewhere", esp: "Nos veremos de nuevo", pro: "ui kan mit aguen sam-uer" },
                        { eng: "Somewhere far away from here", esp: "Lejos de aquí", pro: "sam-uer far a-uei fram jiar" },
                        { eng: "We never learn, we've been here before", esp: "Nunca aprendemos", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "¿Por qué huimos siempre de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "The bullets?", esp: "Las balas", pro: "de bulets" },
                        { eng: "The bullets?", esp: "Las balas", pro: "de bulets" },
                        { eng: "We never learn, we've been here before", esp: "Ya estuvimos aquí", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "¿Por qué huimos de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "The bullets?", esp: "Las balas", pro: "de bulets" },
                        { eng: "The bullets?", esp: "Las balas", pro: "de bulets" },
                        { eng: "Just stop your crying, it's a sign of the times", esp: "Señal de los tiempos", pro: "yost estop iur krain, its a sain ov de taims" },
                        { eng: "We gotta get away from here", esp: "Hay que irnos", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "We gotta get away from here", esp: "Hay que irnos", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "Stop your crying, baby, it'll be alright", esp: "Todo estará bien nena", pro: "estop iur krain, beibi, it-l bi ol-rait" },
                        { eng: "They told me that the end is near", esp: "Fin cerca", pro: "dei told mi dat di end is niar" },
                        { eng: "We gotta get away from here", esp: "Hay que salir", pro: "ui gara guet a-uei fram jiar" },
                        { eng: "We never learn, we've been here before", esp: "No aprendemos", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "¿Por qué huimos de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "Your bullets?", esp: "Tus balas", pro: "iur bulets" },
                        { eng: "The bullets?", esp: "Las balas", pro: "de bulets" },
                        { eng: "We never learn, we've been here before", esp: "Ya estuvimos", pro: "ui never lern, uiv bin jiar bifor" },
                        { eng: "Why are we always stuck and running from", esp: "Huimos de", pro: "uai ar ui ol-ueis estak an ranin fram" },
                        { eng: "Your bullets?", esp: "Tus balas", pro: "iur bulets" },
                        { eng: "Your bullets?", esp: "Tus balas", pro: "iur bulets" },
                        { eng: "We don't talk enough", esp: "No hablamos suficiente", pro: "ui dont tok i-naf" },
                        { eng: "We should open up", esp: "Deberíamos abrirnos", pro: "ui shud oupen ap" },
                        { eng: "Before it's all too much", esp: "Antes de que sea demasiado", pro: "bifor its ol tu mach" },
                        { eng: "Will we ever learn?", esp: "¿Aprenderemos?", pro: "uil ui ever lern" },
                        { eng: "We've been here before", esp: "Ya estuvimos aquí", pro: "uiv bin jiar bifor" },
                        { eng: "It's just what we know", esp: "Es lo que sabemos", pro: "its yost uat ui nou" },
                        { eng: "Stop your crying, baby, it's a sign of the times", esp: "Es la señal", pro: "estop iur krain, beibi, its a sain ov de taims" },
                        { eng: "We gotta get away", esp: "Hay que irse", pro: "ui gara guet a-uei" },
                        { eng: "We got to get away", esp: "Hay que irse", pro: "ui gat tu guet a-uei" },
                        { eng: "We got to get away", esp: "Hay que irse", pro: "ui gat tu guet a-uei" },
                        { eng: "We got to get away", esp: "Hay que irse", pro: "ui gat tu guet a-uei" },
                        { eng: "We got to get away", esp: "Hay que irse", pro: "ui gat tu guet a-uei" },
                        { eng: "We got to, we got to run", esp: "Hay que correr", pro: "ui gat tu ran" },
                        { eng: "We got to, we got to run", esp: "Hay que correr", pro: "ui gat tu ran" },
                        { eng: "We got to, we got to run away", esp: "Hay que huir", pro: "ui gat tu ran a-uei" }
                    ]
                }
            ]
        },
        {
            name: "Robbie Williams", id: "robbie", icon: "🎤",
            songs: [
                {
                    title: "Feel", id: "feel",
                    lyrics: [
                        { eng: "Come on, hold my hand", esp: "Vamos, toma mi mano", pro: "kam on, jold mai jand" },
                        { eng: "I wanna contact the living", esp: "Quiero contactar a los vivos", pro: "ai uana kontakt de livin" },
                        { eng: "Not sure I understand", esp: "No estoy seguro de entender", pro: "not shur ai ander-stand" },
                        { eng: "This role I've been given", esp: "Este papel que me han dado", pro: "dis roul aiv bin guiven" },
                        { eng: "I sit and talk to God", esp: "Me siento y hablo con Dios", pro: "ai sit an tok tu gad" },
                        { eng: "And He just laughs at my plans", esp: "Y él solo se ríe de mis planes", pro: "an ji yost lafs at mai plans" },
                        { eng: "My head speaks a language", esp: "Mi cabeza habla un idioma", pro: "mai jed espiks a langüidsh" },
                        { eng: "I don't understand", esp: "Que no entiendo", pro: "ai dont ander-stand" },
                        { eng: "I just wanna feel real love", esp: "Solo quiero sentir amor real", pro: "ai yost uana fil rial lav" },
                        { eng: "Feel the home that I live in", esp: "Sentir el hogar", pro: "fil de jom dat ai liv in" },
                        { eng: "'Cause I got too much life", esp: "Porque tengo demasiada vida", pro: "kos ai gat tu mach laif" },
                        { eng: "Running through my veins", esp: "Corriendo por mis venas", pro: "ranin thru mai veins" },
                        { eng: "Going to waste", esp: "Yéndose al desperdicio", pro: "gouin tu ueist" },
                        { eng: "I don't wanna die", esp: "No quiero morir", pro: "ai dont uana dai" },
                        { eng: "But I ain't keen on living either", esp: "Tampoco me entusiasma vivir", pro: "bat ai eint kin on livin i-der" },
                        { eng: "Before I fall in love", esp: "Antes de enamorarme", pro: "bifor ai fol in lav" },
                        { eng: "I'm preparing to leave her", esp: "Me preparo para dejarla", pro: "aim priperin tu liv jer" },
                        { eng: "Scare myself to death", esp: "Me muero de miedo", pro: "skear mai-self tu dez" },
                        { eng: "That's why I keep on running", esp: "Por eso sigo corriendo", pro: "dats uai ai kip on ranin" },
                        { eng: "Before I've arrived", esp: "Antes de haber llegado", pro: "bifor aiv araivd" },
                        { eng: "I can see myself coming", esp: "Puedo verme venir", pro: "ai kan si mai-self kamin" },
                        { eng: "I just wanna feel real love", esp: "Sentir amor real", pro: "ai yost uana fil rial lav" },
                        { eng: "Feel the home that I live in", esp: "Sentir el hogar", pro: "fil de jom dat ai liv in" },
                        { eng: "'Cause I got too much life", esp: "Demasiada vida", pro: "kos ai gat tu mach laif" },
                        { eng: "Running through my veins", esp: "Venas", pro: "ranin thru mai veins" },
                        { eng: "Going to waste", esp: "Desperdicio", pro: "gouin tu ueist" },
                        { eng: "And I need to feel real love", esp: "Necesito sentir amor real", pro: "an ai nid tu fil rial lav" },
                        { eng: "And a life ever after", esp: "Vida eterna", pro: "an a laif ever aft-er" },
                        { eng: "I cannot get enough", esp: "No tengo suficiente", pro: "ai kanot guet i-naf" },
                        { eng: "I just wanna feel real love", esp: "Sentir amor real", pro: "ai yost uana fil rial lav" },
                        { eng: "Feel the home that I live in", esp: "El hogar", pro: "fil de jom dat ai liv in" },
                        { eng: "I got too much love", esp: "Tengo mucho amor", pro: "ai gat tu mach lav" },
                        { eng: "Running through my veins", esp: "Venas", pro: "ranin thru mai veins" },
                        { eng: "To go to waste", esp: "Para desperdiciar", pro: "tu gou tu ueist" },
                        { eng: "I just wanna feel real love", esp: "Amor real", pro: "ai yost uana fil rial lav" },
                        { eng: "And a life ever after", esp: "Vida eterna", pro: "an a laif ever aft-er" },
                        { eng: "There's a hole in my soul", esp: "Hueco en mi alma", pro: "ders a jol in mai soul" },
                        { eng: "You can see it in my face", esp: "Se nota en mi cara", pro: "yu kan si it in mai feis" },
                        { eng: "It's a real big place", esp: "Un lugar muy grande", pro: "its a rial big pleis" },
                        { eng: "(Figure it out, feel)", esp: "(Descúbrelo, siente)", pro: "figuier it aut, fil" },
                        { eng: "Come and hold my hand", esp: "Toma mi mano", pro: "kam an jold mai jand" },
                        { eng: "I wanna contact the living", esp: "Contactar a los vivos", pro: "ai uana kontakt de livin" },
                        { eng: "Not sure I understand", esp: "No entiendo", pro: "not shur ai ander-stand" },
                        { eng: "This role I've been given", esp: "Este papel", pro: "dis roul aiv bin guiven" },
                        { eng: "Not sure I understand", esp: "No entiendo", pro: "not shur ai ander-stand" },
                        { eng: "Not sure I understand", esp: "No entiendo", pro: "not shur ai ander-stand" },
                        { eng: "Not sure I understand", esp: "No entiendo", pro: "not shur ai ander-stand" },
                        { eng: "Not sure I understand", esp: "No entiendo", pro: "not shur ai ander-stand" }
                    ]
                }
            ]
        },
        {
            name: "Alicia Keys", id: "alicia_keys", icon: "🎹",
            songs: [
                {
                    title: "Empire State of Mind", id: "empire",
                    lyrics: [
                        { eng: "Ooh, New York", esp: "Ooh, Nueva York", pro: "uuh, nu iork" },
                        { eng: "Ooh, New York", esp: "Ooh, Nueva York", pro: "uuh, nu iork" },
                        { eng: "Grew up in a town that is famous as a place of movie scenes", esp: "Crecí en un pueblo famoso por el cine", pro: "gru ap in a taun dat is feimos as a pleis ov muvi sins" },
                        { eng: "Noise is always loud, there are sirens all around and the streets are mean", esp: "Ruido, sirenas y calles crueles", pro: "nois is ol-ueis laud, der ar sairens ol araund an de estrits ar min" },
                        { eng: "If I can make it here, I can make it anywhere, that's what they say", esp: "Si puedo aquí, puedo donde sea", pro: "if ai kan meik it jiar, ai kan meik it eni-uer, dats uat dei sei" },
                        { eng: "Seein' my face in lights or my name on marquees found down on Broadway", esp: "Viendo mi cara en luces de Broadway", pro: "siin mai feis in laits or mai neim on markis faund daun on bruad-uei" },
                        { eng: "Even if it ain't all it seems, I got a pocketful of dreams", esp: "Aunque no sea lo que parece, tengo sueños", pro: "iven if it eint ol it sims, ai gad a poketful ov drims" },
                        { eng: "Baby, I'm from New York", esp: "Cariño, soy de Nueva York", pro: "beibi, aim fram nu iork" },
                        { eng: "Concrete jungle where dreams are made of", esp: "Jungla de asfalto donde nacen los sueños", pro: "kon-krit yan-gal uer drims ar meid ov" },
                        { eng: "There's nothin' you can't do", esp: "No hay nada que no puedas hacer", pro: "ders na-tin yu kant du" },
                        { eng: "Now you're in New York", esp: "Ahora estás en Nueva York", pro: "nau iur in nu iork" },
                        { eng: "These streets will make you feel brand new", esp: "Estas calles te harán sentir nuevo", pro: "dis estrits uil meik yu fil brand niu" },
                        { eng: "Big lights will inspire you", esp: "Luces grandes te inspirarán", pro: "big laits uil inspai-ar yu" },
                        { eng: "Hear it for New York, New York, New York", esp: "Óyelo por Nueva York", pro: "jiar it for nu iork, nu iork, nu iork" },
                        { eng: "On the avenue, there ain't ever a curfew, ladies work so hard", esp: "Sin toque de queda, mujeres trabajan duro", pro: "on di aveniu, der eint ever a kerfiu, leidis uork sou jard" },
                        { eng: "Such a meltin' pot, on the corner sellin' rock, preachers pray to God", esp: "Crisol, vendiendo droga, rezan", pro: "sach a meltin pot, on de korner selin rok, prichers prei tu gad" },
                        { eng: "Hail a gypsy cab, takes me down from Harlem to the Brooklyn Bridge", esp: "Tomo un taxi de Harlem al puente", pro: "jeil a yipsi kab, teiks mi daun fram jarlem tu de bruklin bridsh" },
                        { eng: "Someone sleeps tonight with a hunger far more than an empty fridge", esp: "Dormir con hambre y nevera vacía", pro: "sam-uan eslips tunaid uid a jánguer far mor dan an emti fridsh" },
                        { eng: "I'ma make it by any means, I got a pocketful of dreams", esp: "Lo lograré como sea", pro: "aima meik it bai eni mins, ai gad a poketful ov drims" },
                        { eng: "Baby, I'm from New York", esp: "Soy de Nueva York", pro: "beibi, aim fram nu iork" },
                        { eng: "Concrete jungle where dreams are made of", esp: "Jungla de asfalto", pro: "kon-krit yan-gal uer drims ar meid ov" },
                        { eng: "There's nothin' you can't do", esp: "Nada imposible", pro: "ders na-tin yu kant du" },
                        { eng: "Now you're in New York", esp: "Estás en Nueva York", pro: "nau iur in nu iork" },
                        { eng: "These streets will make you feel brand new", esp: "Sentirse nuevo", pro: "dis estrits uil meik yu fil brand niu" },
                        { eng: "Big lights will inspire you", esp: "Luces te inspirarán", pro: "big laits uil inspai-ar yu" },
                        { eng: "Hear it for New York, New York, New York", esp: "Óyelo por Nueva York", pro: "jiar it for nu iork, nu iork, nu iork" },
                        { eng: "One hand in the air for the Big City", esp: "Mano arriba por la Gran Ciudad", pro: "uan jand in di er for de big siti" },
                        { eng: "Streetlights, big dreams, all lookin' pretty", esp: "Luces, sueños grandes", pro: "estrit-laits, big drims, ol lukin priti" },
                        { eng: "No place in the world that can compare", esp: "Nada se le compara", pro: "nou pleis in de uorld dat kan komper" },
                        { eng: "Put your lighters in the air, everybody say: Yeah, yeah", esp: "Encendedores arriba", pro: "put iur laiters in di er, evribadi sei: ié, ié" },
                        { eng: "Yeah, yeah", esp: "Sí, sí", pro: "ié, ié" },
                        { eng: "In New York", esp: "En Nueva York", pro: "in nu iork" },
                        { eng: "Concrete jungle where dreams are made of", esp: "Jungla de concreto", pro: "kon-krit yan-gal uer drims ar meid ov" },
                        { eng: "There's nothin' you can't do", esp: "Nada imposible", pro: "ders na-tin yu kant du" },
                        { eng: "Now you're in New York", esp: "Estás en NY", pro: "nau iur in nu iork" },
                        { eng: "These streets will make you feel brand-new", esp: "Sentirse nuevo", pro: "dis estrits uil meik yu fil brand-niu" },
                        { eng: "Big lights will inspire you", esp: "Luces inspiran", pro: "big laits uil inspai-ar yu" },
                        { eng: "Hear it for New York", esp: "Óyelo por Nueva York", pro: "jiar it for nu iork" }
                    ]
                }
            ]
        }
    ],
    categories: {
        reactions: [
            { eng: "Damn!", esp: "¡Rayos! / ¡Wow!", pro: "dam!" },
            { eng: "Hell yeah!", esp: "¡Claro que sí!", pro: "jel ié!" },
            { eng: "What the hell?", esp: "¿Qué demonios?", pro: "uat de jel?" },
            { eng: "Damnit!", esp: "¡Maldita sea!", pro: "dam-nit!" },
            { eng: "No hell way!", esp: "¡De ninguna manera!", pro: "nou jel uei!" },
            { eng: "For sure!", esp: "¡Totalmente!", pro: "for shur" },
            { eng: "Facts!", esp: "¡Exacto!", pro: "fakts!" },
            { eng: "Goddamn!", esp: "¡Maldición!", pro: "gad-dam!" },
            { eng: "What’s good?", esp: "¿Quieres pelea?", pro: "uats gud?" },
            { eng: "Pull up!", esp: "¡Ven aquí! (Desafío)", pro: "pul ap!" },
            { eng: "Square up!", esp: "¡Ponte en guardia!", pro: "eskuer ap!" },
            { eng: "Keep that same energy!", esp: "¡Mantén esa actitud!", pro: "kip dat seim éneryi!" },
            { eng: "Try me!", esp: "¡Atrevete!", pro: "trai mi!" },
            { eng: "You’re food.", esp: "Eres presa fácil", pro: "iur fud." },
            { eng: "Don’t play with me!", esp: "¡No juegues conmigo!", pro: "dont plei uid mi!" },
            { eng: "You want smoke?", esp: "¿Quieres problemas?", pro: "yu uant esmouk?" },
            { eng: "Catch these hands!", esp: "¡Te voy a golpear!", pro: "kach dis jands!" },
            { eng: "Run your pockets!", esp: "¡Dame todo! (Robo)", pro: "ran iur pokets!" },
            { eng: "You’re a dub.", esp: "Eres un fracaso", pro: "iur a dab." },
            { eng: "You’re buggin’.", esp: "Estás loco", pro: "iur baguin." },
            { eng: "Get out of my face!", esp: "¡Quítate de mi vista!", pro: "guet aut ov mai feis!" },
            { eng: "Stop cappin’!", esp: "¡Deja de mentir!", pro: "estop kapin!" },
            { eng: "You’re reaching!", esp: "¡Estás inventando!", pro: "iur richin!" },
            { eng: "Shut your trap!", esp: "¡Cierra el pico!", pro: "shat iur trap!" },
            { eng: "Take a hike!", esp: "¡Lárgate!", pro: "teik a jaik!" },
            { eng: "F outta here!", esp: "¡Fuera de aquí!", pro: "ef aut-a jiar!" },
            { eng: "You’re a clown.", esp: "Eres un payaso", pro: "iur a klaun." },
            { eng: "Deadass, move!", esp: "¡En serio, muévete!", pro: "ded-as, muv!" },
            { eng: "Go to hell!", esp: "¡Vete al infierno!", pro: "gou tu jel!" },
            { eng: "Hell to pay!", esp: "Habrá consecuencias", pro: "jel tu pei!" },
            { eng: "Burn in hell!", esp: "¡Púdrete!", pro: "bern in jel!" },
            { eng: "To hell with you!", esp: "¡Al carajo contigo!", pro: "tu jel uid yu!" },
            { eng: "Hell on earth.", esp: "Infierno en la tierra", pro: "jel on erz." },
            { eng: "Raising hell.", esp: "Armar un escándalo", pro: "reisin jel." },
            { eng: "Like a bat out of hell.", esp: "A toda velocidad", pro: "laik a bat aut ov jel." },
            { eng: "Hellish!", esp: "¡Infernal!", pro: "jel-ish!" },
            { eng: "Worldstar!", esp: "¡Grito de pelea viral!", pro: "uorld-estar!" },
            { eng: "He’s leaking!", esp: "Está sangrando", pro: "jis likin!" },
            { eng: "He got rocked!", esp: "Le dieron duro", pro: "ji gat rokt!" },
            { eng: "Knock his lights out!", esp: "¡Noquéalo!", pro: "nok jis laits aut!" },
            { eng: "Oh, he’s done!", esp: "¡Se acabó para él!", pro: "ou, jis dan!" },
            { eng: "He’s sleep!", esp: "Quedó inconsciente", pro: "jis eslip!" },
            { eng: "Starch him!", esp: "Déjalo tieso", pro: "estarch jim!" },
            { eng: "Body him!", esp: "Derrótalo totalmente", pro: "badi jim!" },
            { eng: "He’s getting washed.", esp: "Le están ganando fácil", pro: "jis guetin uash-d." },
            { eng: "Folded him!", esp: "Lo dobló del golpe", pro: "foulded jim!" },
            { eng: "Jesus H. Christ!", esp: "¡Jesucristo! (Enojo)", pro: "yisus eish kraist!" },
            { eng: "Good God Almighty!", esp: "¡Dios Todopoderoso!", pro: "gud gad ol-maiti!" },
            { eng: "Lord have mercy!", esp: "¡Señor ten piedad!", pro: "lord jav mersi!" },
            { eng: "Sweet mother of God!", esp: "¡Santa madre de Dios!", pro: "suit mader ov gad!" },
            { eng: "God as my witness!", esp: "¡Dios como mi testigo!", pro: "gad as mai uid-nes!" },
            { eng: "For the love of God!", esp: "¡Por el amor de Dios!", pro: "for de lav ov gad!" },
            { eng: "Holy mother!", esp: "¡Santa madre!", pro: "jouli mader!" },
            { eng: "Heaven help us!", esp: "¡Que el cielo nos ayude!", pro: "jeven jelp as!" },
            { eng: "Christ on a cracker!", esp: "¡Cristo bendito!", pro: "kraist on a kraker!" },
            { eng: "God strike me down!", esp: "¡Que Dios me fulmine!", pro: "gad estraik mi daun!" }
        ],
        danger: [
            { eng: "Watch out!", esp: "¡Cuidado!", pro: "uatch aut" },
            { eng: "Heads up!", esp: "¡Ojo! / ¡Atención!", pro: "jeds ap" },
            { eng: "Get down!", esp: "¡Al suelo!", pro: "guet daun" },
            { eng: "Run!", esp: "¡Corre!", pro: "ran" },
            { eng: "Duck!", esp: "¡Agáchate!", pro: "dak" },
            { eng: "Freeze!", esp: "¡Quieto!", pro: "friz" },
            { eng: "They're strapped", esp: "Están armados", pro: "deir estrap-t" },
            { eng: "It's a setup", esp: "Es una trampa", pro: "its a set-ap" },
            { eng: "Beat it!", esp: "¡Lárgate!", pro: "bit it" }
        ],
        money: [
            { eng: "Get that bag", esp: "Haz ese dinero", pro: "guet dat bag" },
            { eng: "I'm broke", esp: "No tengo dinero", pro: "aim brouk" },
            { eng: "Bread / Dough", esp: "Dinero", pro: "bred / dou" },
            { eng: "Hustle hard", esp: "Esfuérzate al máximo", pro: "jas-el jard" },
            { eng: "Grind never stops", esp: "El esfuerzo no para", pro: "graind never estops" },
            { eng: "Shady deal", esp: "Negocio turbio", pro: "sheidi dil" },
            { eng: "A grand / A stack", esp: "Mil dólares", pro: "a grand / a estak" },
            { eng: "Launder the money", esp: "Lavar el dinero", pro: "lon-der de mani" },
            { eng: "Keep it on the low", esp: "Mantenlo en secreto", pro: "kip it on de lou" }
        ],
        bodega: [
            { eng: "Yo, Ock!", esp: "¡Oye, amigo! (Al tendero)", pro: "yo, ok!" },
            { eng: "Lemme get a...", esp: "Dame un...", pro: "lemi guet a" },
            { eng: "Deadass?", esp: "¿En serio? / ¿De verdad?", pro: "ded-as?" },
            { eng: "Keep the change", esp: "Quédate con el cambio", pro: "kip de cheinj" },
            { eng: "That's valid", esp: "Eso es de calidad", pro: "dats valid" },
            { eng: "You buggin'!", esp: "¡Estás loco! / Exageras", pro: "yu baguin!" }
        ],
        subway: [
            { eng: "Watch the gap", esp: "Cuidado con el hueco", pro: "uatch de gap" },
            { eng: "Step back from the doors", esp: "Aléjese de las puertas", pro: "estep bak fram de dors" },
            { eng: "Uptown or Downtown?", esp: "¿Hacia el norte o sur?", pro: "ap-taun or daun-taun?" },
            { eng: "The train is delayed", esp: "El tren está retrasado", pro: "de trein is di-leid" },
            { eng: "Excuse me, lemme past", esp: "Permiso, déjeme pasar", pro: "exkius mi, lemi past" }
        ],
        slang: [
            { eng: "Alright", esp: "Todo bien", pro: "ol-rait" },
            { eng: "Body him", esp: "Derrótalo", pro: "badi jim" },
            { eng: "Buggin'", esp: "Estar loco", pro: "baguin" },
            { eng: "Deadass", esp: "En serio / Verdad", pro: "ded-as" },
            { eng: "Facts", esp: "Es la verdad", pro: "fakts" },
            { eng: "Hustle", esp: "Buscavidas / Trabajo", pro: "jas-el" },
            { eng: "No Cap", esp: "Sin mentiras", pro: "nou kap" },
            { eng: "Valid", esp: "Bueno", pro: "valid" },
            { eng: "Yo!", esp: "Oye / Hola", pro: "yo!" },
            { eng: "Concrete", esp: "Hormigón", pro: "kon-krit" },
            { eng: "Empire", esp: "Imperio", pro: "em-pai-ar" },
            { eng: "Jungle", esp: "Selva", pro: "jan-guel" },
            { eng: "Meltin pot", esp: "Mezcla de culturas", pro: "meltin pot" },
            { eng: "Stray", esp: "Vagar", pro: "estrei" },
            { eng: "Vagabond", esp: "Vagabundo", pro: "va-ga-bond" },
            { eng: "Atmosphere", esp: "Atmósfera", pro: "atmos-fiar" },
            { eng: "Amusing", esp: "Divertido", pro: "amiusing" },
            { eng: "Bullets", esp: "Balas", pro: "bulets" },
            { eng: "Bribe", esp: "Sobornar", pro: "braib" },
            { eng: "Brick", esp: "Mucho frío", pro: "brik" },
            { eng: "Curfew", esp: "Toque de queda", pro: "kerfiu" },
            { eng: "Delayed", esp: "Retrasado", pro: "di-leid" },
            { eng: "Exemption", esp: "Excepción", pro: "eksempshon" },
            { eng: "Fridge", esp: "Nevera", pro: "fridsh" },
            { eng: "Gap", esp: "Hueco", pro: "gap" },
            { eng: "Highway", esp: "Autopista", pro: "jai-uei" },
            { eng: "Inspire", esp: "Inspirar", pro: "inspai-ar" },
            { eng: "Leaking", esp: "Sangrando", pro: "likin" },
            { eng: "Maniac", esp: "Maníaco", pro: "meiniak" },
            { eng: "Pull up", esp: "Llegar", pro: "pul ap" },
            { eng: "Regrets", esp: "Arrepentimientos", pro: "rigrets" },
            { eng: "Rocked", esp: "Noqueado", pro: "rokt" },
            { eng: "Sirens", esp: "Sirenas", pro: "sairens" },
            { eng: "Smoke", esp: "Pelea / Humo", pro: "esmouk" },
            { eng: "Square up", esp: "Pelear", pro: "eskuer ap" },
            { eng: "Trap", esp: "Boca", pro: "trap" },
            { eng: "Uptown", esp: "Norte", pro: "ap-taun" },
            { eng: "Washed", esp: "Derrótado", pro: "uash-d" },
            { eng: "Broke", esp: "Sin dinero", pro: "brouk" },
            { eng: "Bread", esp: "Dinero", pro: "bred" },
            { eng: "Dough", esp: "Dinero", pro: "dou" },
            { eng: "Grand", esp: "Mil dólares", pro: "grand" },
            { eng: "Stack", esp: "Fajo de billetes", pro: "estak" },
            { eng: "Shady", esp: "Turbio", pro: "sheidi" },
            { eng: "Freeze", esp: "Quieto", pro: "friz" },
            { eng: "Duck", esp: "Agacharse", pro: "dak" },
            { eng: "Strapped", esp: "Armado", pro: "estrap-t" },
            { eng: "Setup", esp: "Trampa", pro: "set-ap" },
            { eng: "Beat it", esp: "Lárgate", pro: "bit it" },
            { eng: "Scram", esp: "Fuera", pro: "eskram" },
            { eng: "Witness", esp: "Testigo", pro: "uid-nes" },
            { eng: "Almighty", esp: "Todopoderoso", pro: "ol-maiti" },
            { eng: "Cracker", esp: "Pobre", pro: "kraker" },
            { eng: "Strike", esp: "Castigar", pro: "estraik" },
            { eng: "Naught", esp: "Nada", pro: "not" },
            { eng: "Byway", esp: "Camino", pro: "bai-uei" },
            { eng: "Chew", esp: "Masticar", pro: "chu" },
            { eng: "Tall", esp: "Alto", pro: "tol" },
            { eng: "Subside", esp: "Disminuir", pro: "sab-said" },
            { eng: "Shy", esp: "Tímido", pro: "shai" },
            { eng: "Curtain", esp: "Cortina", pro: "ker-ten" },
            { eng: "Highway", esp: "Carretera", pro: "jai-uei" },
            { eng: "Regret", esp: "Arrepentimiento", pro: "ri-gret" },
            { eng: "Mention", esp: "Mencionar", pro: "men-shon" },
            { eng: "Charted", esp: "Trazado", pro: "char-ted" },
            { eng: "Byway", esp: "Atajo", pro: "bai-uei" },
            { eng: "Chew", esp: "Morder", pro: "chu" },
            { eng: "Amusing", esp: "Divertido", pro: "a-miu-sing" },
            { eng: "Kneels", esp: "Arrodillarse", pro: "ni-ls" },
            { eng: "Marquees", esp: "Marquesinas", pro: "mar-kis" },
            { eng: "Curfew", esp: "Toque de queda", pro: "ker-fiu" },
            { eng: "Gypsy", esp: "Taxi pirata", pro: "yipsi" },
            { eng: "Fridge", esp: "Refrigerador", pro: "fridsh" },
            { eng: "Keen", esp: "Interesado", pro: "ki-n" },
            { eng: "Arrived", esp: "Llegado", pro: "a-raiv-d" },
            { eng: "Bribe", esp: "Sobornar", pro: "braib" },
            { eng: "Atmosphere", esp: "Atmósfera", pro: "at-mos-fiar" },
            { eng: "Bullet", esp: "Bala", pro: "bu-let" },
            { eng: "Stuck", esp: "Atrapado", pro: "stak" },
            { eng: "Crying", esp: "Llorar", pro: "krain" }
        ]
    }
};