const data = {
    artists: [
        {
            name: "Frank Sinatra", id: "sinatra", icon: "🎩",
            songs: [
                {
                    title: "My Way", id: "my_way",
                    lyrics: [
                        { e: "And now, the end is near", p: "an nau, di end is niar", s: "Y ahora, el final está cerca" },
                        { e: "And so I face the final curtain", p: "an sou ai feis de fainal kerten", s: "Y así enfrento el telón final" },
                        { e: "My friend, I'll say it clear", p: "mai frend, ail sei it kliar", s: "Mi amigo, lo diré claramente" },
                        { e: "I'll state my case, of which I'm certain", p: "ail steit mai keis, ov uich aim serten", s: "Expondré mi caso, del cual estoy seguro" },
                        { e: "I've lived a life that's full", p: "aiv livd a laif dats ful", s: "He vivido una vida plena" },
                        { e: "I travelled each and every highway", p: "ai traveld ich an evri jai-uei", s: "Viajé por todas y cada una de las carreteras" },
                        { e: "And more, much more than this", p: "an mor, mach mor dan dis", s: "Y más, mucho más que esto" },
                        { e: "I did it my way", p: "ai did it mai uei", s: "Lo hice a mi manera" },
                        { e: "Regrets, I've had a few", p: "rigrets, aiv jad a fiu", s: "Arrepentimientos, tuve algunos" },
                        { e: "But then again, too few to mention", p: "bat den aguen, tu fiu tu menshon", s: "Pero muy pocos para mencionar" },
                        { e: "I did what I had to do", p: "ai did uat ai jad tu du", s: "Hice lo que tenía que hacer" },
                        { e: "And saw it through without exemption", p: "an so it thru uid-aut eksempshon", s: "Y lo logré sin excepciones" },
                        { e: "I planned each charted course", p: "ai pland ich charted kors", s: "Planifiqué cada curso trazado" },
                        { e: "Each careful step along the byway", p: "ich kerful estep a-lon de bai-uei", s: "Cada paso cuidadoso por el camino" },
                        { e: "And more, much more than this", p: "an mor, mach mor dan dis", s: "Y más, mucho más que esto" },
                        { e: "I did it my way", p: "ai did it mai uei", s: "Lo hice a mi manera" },
                        { e: "Yes, there were times, I'm sure you knew", p: "ies, der uer taims, aim shur yu niu", s: "Sí, hubo momentos, seguro lo sabías" },
                        { e: "When I bit off more than I could chew", p: "uen ai bit of mor dan ai kul chu", s: "Cuando mordí más de lo que podía masticar" },
                        { e: "But through it all, when there was doubt", p: "bat thru it ol, uen der uas daut", s: "Pero en todo, cuando hubo duda" },
                        { e: "I ate it up and spit it out", p: "ai eit it ap an espit it aut", s: "Lo engullí y lo escupí" },
                        { e: "I faced it all and I stood tall", p: "ai feist it ol an ai estud tol", s: "Lo enfrenté y me mantuve firme" },
                        { e: "And did it my way", p: "ai did it mai uei", s: "Y lo hice a mi manera" },
                        { e: "I've loved, I've laughed and cried", p: "aiv lavd, aiv laft an kraid", s: "He amado, reído y llorado" },
                        { e: "I've had my fill, my share of losing", p: "aiv jad mai fill, mai sher ov lusin", s: "Tuve mi parte de pérdida" },
                        { e: "And now, as tears subside", p: "an nau, as tiars sabsid", s: "Y ahora, al calmarse las lágrimas" },
                        { e: "I find it all so amusing", p: "ai faind it ol sou amiusing", s: "Lo encuentro muy divertido" },
                        { e: "To think I did all that", p: "tu dink ai did ol dat", s: "Pensar que hice todo eso" },
                        { e: "And may I say, not in a shy way", p: "an mei ai sei, not in a shai uei", s: "Y no de manera tímida" },
                        { e: "Oh, no, oh, no, not me", p: "ou nou, ou nou, not mi", s: "Oh no, yo no" },
                        { e: "I did it my way", p: "ai did it mai uei", s: "Lo hice a mi manera" },
                        { e: "For what is a man, what has he got?", p: "for uat is a man, uat jas ji gat", s: "¿Qué es un hombre? ¿qué tiene?" },
                        { e: "If not himself, then he has naught", p: "if not jim-self, den ji jas not", s: "Si no se tiene a sí mismo, no tiene nada" },
                        { e: "To say the things he truly feels", p: "tu sei de dings ji truli fils", s: "Decir lo que realmente siente" },
                        { e: "And not the words of one who kneels", p: "an not de uords ov uan ju nils", s: "Y no las palabras de uno que se arrodilla" },
                        { e: "The record shows I took the blows", p: "de rekord shous ai tuk de blous", s: "El historial muestra que acepté los golpes" },
                        { e: "And did it my way", p: "ai did it mai uei", s: "Lo hice a mi manera" },
                        { e: "Yes, it was my way", p: "ies, it uas mai uei", s: "Sí, fue a mi manera" }
                    ]
                },
                {
                    title: "New York, New York", id: "ny_ny",
                    lyrics: [
                        { e: "Start spreading the news", p: "stard espredin de nius", s: "Empiecen a difundir las noticias" },
                        { e: "I'm leaving today", p: "aim livin tudei", s: "Me voy hoy mismo" },
                        { e: "I want to be part of it", p: "ai uant tu bi pard ov it", s: "Quiero ser parte" },
                        { e: "New York, New York", p: "nu iork, nu iork", s: "Nueva York, Nueva York" },
                        { e: "These vagabond shoes", p: "dis vagabond shus", s: "Estos zapatos de vagabundo" },
                        { e: "Are longing to stray", p: "ar lon-guin tu estrei", s: "Desean vagar" },
                        { e: "Right through the very heart of it", p: "rait thru de veri jart ov it", s: "Por el corazón de ella" },
                        { e: "New York, New York", p: "nu iork, nu iork", s: "Nueva York" },
                        { e: "I wanna wake up in that city", p: "ai uana ueik ap in dat siti", s: "Quiero despertar en esa ciudad" },
                        { e: "That doesn't sleep", p: "dat dasent eslip", s: "Que no duerme" },
                        { e: "And find I'm king of the hill", p: "an faind aim kin ov de jil", s: "Ser el rey" },
                        { e: "Top of the heap", p: "top ov de jip", s: "En la cima" },
                        { e: "These little town blues", p: "dis litel taun blus", s: "Penas de pueblo" },
                        { e: "Are melting away", p: "ar meltin a-uei", s: "Se esfuman" },
                        { e: "I'll make a brand-new start of it", p: "ail meik a brand-niu estart", s: "Un nuevo comienzo" },
                        { e: "In old New York", p: "in ould nu iork", s: "En la vieja NY" },
                        { e: "If I can make it there", p: "if ai kan meik it der", s: "Si lo logro allá" },
                        { e: "I'll make it anywhere", p: "ail meik it eni-uer", s: "Lo lograré en cualquier parte" },
                        { e: "It's up to you", p: "its ap tu yu", s: "Depende de ti" },
                        { e: "New York, New York", p: "nu iork, nu iork", s: "Nueva York" },
                        { e: "New York, New York", p: "nu iork, nu iork", s: "Nueva York" },
                        { e: "I want to wake up", p: "ai uant tu ueik ap", s: "Despertar" },
                        { e: "In a city that never sleeps", p: "in a siti dat never eslips", s: "Ciudad que nunca duerme" },
                        { e: "And find I'm a number one", p: "an faind aim a namber uan", s: "Ser el número uno" },
                        { e: "Top of the list", p: "top ov de list", s: "Primero en la lista" },
                        { e: "King of the hill", p: "kin ov de jil", s: "Rey de la colina" },
                        { e: "A number one", p: "a namber uan", s: "Número uno" },
                        { e: "These little town blues", p: "dis litel taun blus", s: "Penas de pueblo" },
                        { e: "Are melting away", p: "ar meltin a-uei", s: "Se esfuman" },
                        { e: "I'm gonna make a brand-new start of it", p: "aim gana meik a brand-niu estart", s: "Nuevo comienzo" },
                        { e: "In old New York", p: "in ould nu iork", s: "En la vieja NY" },
                        { e: "And if I can make it there", p: "an if ai kan meik it der", s: "Si lo logro allá" },
                        { e: "You know I'm gonna make it anywhere", p: "yu nou aim gana meik it eni-uer", s: "Sabes que lo lograré en cualquier parte" },
                        { e: "It's up to you", p: "its ap tu yu", s: "Depende de ti" },
                        { e: "New York, New York!", p: "nu iork, nu iork!", s: "¡Nueva York!" },
                        { e: "New York!", p: "nu iork!", s: "¡Nueva York!" }
                    ]
                }
            ]
        },
        {
            name: "Alicia Keys", id: "alicia_keys", icon: "🎹",
            songs: [
                {
                    title: "Empire State of Mind", id: "empire",
                    lyrics: [
                        { e: "Ooh, New York", p: "uu, nu iork", s: "Ooh, Nueva York" },
                        { e: "Ooh, New York", p: "uu, nu iork", s: "Ooh, Nueva York" },
                        { e: "Grew up in a town that is famous as a place of movie scenes", p: "gru ap in a taun...", s: "Crecí en un pueblo famoso por el cine" },
                        { e: "Noise is always loud, there are sirens all around and the streets are mean", p: "nois is ol-ueis laud...", s: "Mucho ruido, sirenas y calles crueles" },
                        { e: "If I can make it here, I can make it anywhere, that's what they say", p: "if ai kan meik it jiar...", s: "Si puedo aquí, puedo en cualquier lugar" },
                        { e: "Seein' my face in lights or my name on marquees found down on Broadway", p: "siin mai feis in laits...", s: "Viendo mi cara en luces o marquesinas de Broadway" },
                        { e: "Even if it ain't all it seems, I got a pocketful of dreams", p: "iven if it eint ol...", s: "Aunque no sea lo que parece, tengo sueños" },
                        { e: "Baby, I'm from New York", p: "beibi, aim fram nu iork", s: "Soy de Nueva York" },
                        { e: "Concrete jungle where dreams are made of", p: "kon-krit jánguel...", s: "Jungla de asfalto donde nacen los sueños" },
                        { e: "There's nothin' you can't do", p: "ders natin yu kent du", s: "No hay nada que no puedas hacer" },
                        { e: "Now you're in New York", p: "nau iur in nu iork", s: "Ahora estás en Nueva York" },
                        { e: "These streets will make you feel brand new", p: "dis estrits uil meik yu fil brand niu", s: "Estas calles te harán sentir nuevo" },
                        { e: "Big lights will inspire you", p: "big laits uil inspai-ar yu", s: "Luces grandes te inspirarán" },
                        { e: "Hear it for New York, New York, New York", p: "jiar it for nu iork...", s: "Óyelo por Nueva York" },
                        { e: "On the avenue, there ain't ever a curfew, ladies work so hard", p: "on di aveniu...", s: "En la avenida no hay toque de queda, mujeres trabajan duro" },
                        { e: "Such a meltin' pot, on the corner sellin' rock, preachers pray to God", p: "sach a meltin pot...", s: "Un crisol, vendiendo droga, predicadores rezan" },
                        { e: "Hail a gypsy cab, takes me down from Harlem to the Brooklyn Bridge", p: "jeil a yipsi kab...", s: "Tomo un taxi de Harlem al puente de Brooklyn" },
                        { e: "Someone sleeps tonight with a hunger far more than an empty fridge", p: "sam-uan eslips tunaid...", s: "Dormir con hambre y nevera vacía" },
                        { e: "I'ma make it by any means, I got a pocketful of dreams", p: "aima meik it bai eni mins...", s: "Lo lograré como sea, tengo sueños" },
                        { e: "Baby, I'm from New York", p: "beibi...", s: "Soy de Nueva York" },
                        { e: "Concrete jungle where dreams are made of", p: "kon-krit jánguel...", s: "Jungla de asfalto" },
                        { e: "There's nothin' you can't do", p: "ders natin...", s: "Nada imposible" },
                        { e: "Now you're in New York", p: "nau iur...", s: "Estás en NY" },
                        { e: "These streets will make you feel brand new", p: "dis estrits...", s: "Sentirse nuevo" },
                        { e: "Big lights will inspire you", p: "big laits...", s: "Luces te inspiran" },
                        { e: "Hear it for New York, New York, New York", p: "jiar it...", s: "Por Nueva York" },
                        { e: "One hand in the air for the Big City", p: "uan jand in di er...", s: "Mano arriba por la Gran Ciudad" },
                        { e: "Streetlights, big dreams, all lookin' pretty", p: "estrit-laits, big drims...", s: "Luces, sueños, todo se ve bien" },
                        { e: "No place in the world that can compare", p: "nou pleis in de uorld...", s: "Ningún lugar en el mundo se compara" },
                        { e: "Put your lighters in the air, everybody say: Yeah, yeah", p: "put iur laiters...", s: "Encendedores arriba, todos digan: Sí, sí" },
                        { e: "Yeah, yeah", p: "ié, ié", s: "Sí, sí" },
                        { e: "In New York", p: "in nu iork", s: "En Nueva York" },
                        { e: "Concrete jungle where dreams are made of", p: "kon-krit jánguel...", s: "Jungla de asfalto" },
                        { e: "There's nothin' you can't do", p: "ders natin...", s: "Nada imposible" },
                        { e: "Now you're in New York", p: "nau iur...", s: "Estás en NY" },
                        { e: "These streets will make you feel brand-new", p: "dis estrits...", s: "Sentirse nuevo" },
                        { e: "Big lights will inspire you", p: "big laits...", s: "Luces te inspiran" },
                        { e: "Hear it for New York", p: "jiar it...", s: "Óyelo por NY" }
                    ]
                }
            ]
        },
        {
            name: "Robbie Williams", id: "robbie", icon: "🎤",
            songs: [
                {
                    title: "Feel", id: "feel",
                    lyrics: [
                        { e: "Come on, hold my hand", p: "kam on, jold mai jand", s: "Toma mi mano" },
                        { e: "I wanna contact the living", p: "ai uana kontakt de livin", s: "Contactar vivos" },
                        { e: "Not sure I understand", p: "not shur ai ander-stand", s: "No entiendo bien" },
                        { e: "This role I've been given", p: "dis roul aiv bin guiven", s: "Este papel" },
                        { e: "I sit and talk to God", p: "ai sit an tok tu gad", s: "Hablo con Dios" },
                        { e: "And He just laughs at my plans", p: "an ji yost lafs at mai plans", s: "Él se ríe" },
                        { e: "My head speaks a language", p: "mai jed espiks a langüidsh", s: "Idioma" },
                        { e: "I don't understand", p: "ai dont ander-stand", s: "Que no entiendo" },
                        { e: "I just wanna feel real love", p: "ai yost uana fil rial lav", s: "Sentir amor real" },
                        { e: "Feel the home that I live in", p: "fil de jom dat ai liv in", s: "Sentir mi hogar" },
                        { e: "Cause I got too much life", p: "kos ai gat tu mach laif", s: "Tengo mucha vida" },
                        { e: "Running through my veins", p: "ranin thru mai veins", s: "Por mis venas" },
                        { e: "Going to waste", p: "gouin tu ueist", s: "Desperdiciándose" },
                        { e: "I don't wanna die", p: "ai dont uana dai", s: "No morir" },
                        { e: "But I ain't keen on living either", p: "bat ai eint kin on livin i-der", s: "Pero tampoco quiero vivir" },
                        { e: "Before I fall in love", p: "bifor ai fol in lav", s: "Antes de enamorarme" },
                        { e: "I'm preparing to leave her", p: "aim priperin tu liv jer", s: "Me preparo para dejarla" },
                        { e: "Scare myself to death", p: "skear mai-self tu dez", s: "Me muero de miedo" },
                        { e: "That's why I keep on running", p: "dats uai ai kip on ranin", s: "Por eso sigo corriendo" },
                        { e: "Before I've arrived", p: "bifor aiv araivd", s: "Antes de haber llegado" },
                        { e: "I can see myself coming", p: "ai kan si mai-self kamin", s: "Puedo verme venir" },
                        { e: "I just wanna feel real love", p: "ai yost uana fil...", s: "Amor real" },
                        { e: "Feel the home that I live in", p: "fil de jom...", s: "Mi hogar" },
                        { e: "Cause I got too much life", p: "kos ai gat...", s: "Mucha vida" },
                        { e: "Running through my veins", p: "ranin thru...", s: "Venas" },
                        { e: "Going to waste", p: "gouin tu ueist", s: "Desperdicio" },
                        { e: "And I need to feel real love", p: "an ai nid tu fil...", s: "Necesito amor" },
                        { e: "And a life ever after", p: "an a laif ever aft-er", s: "Vida eterna" },
                        { e: "I cannot get enough", p: "ai kanot guet i-naf", s: "No basta" },
                        { e: "I just wanna feel real love", p: "ai yost uana fil...", s: "Amor real" },
                        { e: "Feel the home that I live in", p: "fil de jom...", s: "Hogar" },
                        { e: "I got too much love", p: "ai gat tu mach lav", s: "Mucho amor" },
                        { e: "Running through my veins", p: "ranin thru...", s: "Venas" },
                        { e: "To go to waste", p: "tu gou tu ueist", s: "Para desperdiciar" },
                        { e: "I just wanna feel real love", p: "ai yost uana fil...", s: "Amor real" },
                        { e: "And a life ever after", p: "an a laif ever aft-er", s: "Vida eterna" },
                        { e: "There's a hole in my soul", p: "ders a jol in mai soul", s: "Hueco" },
                        { e: "You can't see it in my face", p: "yu kan si it in mai feis", s: "Cara" },
                        { e: "It's a real big place", p: "its a rial big pleis", s: "Lugar grande" },
                        { e: "Come and hold my hand", p: "kam an jold mai jand", s: "Mano" },
                        { e: "I wanna contact the living", p: "ai uana kontakt...", s: "Contactar vivos" },
                        { e: "Not sure I understand", p: "not shur ai...", s: "No entiendo" },
                        { e: "This role I've been given", p: "dis roul...", s: "Este papel" },
                        { e: "Not sure I understand", p: "not shur...", s: "No entiendo" },
                        { e: "Not sure I understand", p: "not shur...", s: "No entiendo" },
                        { e: "Not sure I understand", p: "not shur...", s: "No entiendo" },
                        { e: "Not sure I understand", p: "not shur ai ander-stand", s: "No estoy seguro" }
                    ]
                }
            ]
        },
        {
            name: "Harry Styles", id: "harry_styles", icon: "🕺",
            songs: [
                {
                    title: "Sign of the Times", id: "sign_times",
                    lyrics: [
                        { e: "Just stop your crying, it's a sign of the times", p: "yost estop iur krain...", s: "Deja de llorar, señal de los tiempos" },
                        { e: "Welcome to the final show", p: "uel-kam tu de fainal shou", s: "Show final" },
                        { e: "Hope you're wearing your best clothes", p: "joup iur uerin iur best klous", s: "Mejor ropa" },
                        { e: "You can't bribe the door on your way to the sky", p: "yu kant braib de dor...", s: "No puedes sobornar" },
                        { e: "You look pretty good down here", p: "yu luk priti gud...", s: "Te ves bien" },
                        { e: "But you ain't really good", p: "bat yu eint rili gud", s: "No eres bueno" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "Ya estuvimos aquí" },
                        { e: "Why are we always stuck and running from the bullets?", p: "uai ar ui ol-ueis estak an ranin fram de bulets", s: "¿Por qué huimos de las balas?" },
                        { e: "The bullets?", p: "de bulets", s: "Balas" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "No aprendemos" },
                        { e: "Why are we always stuck and running from your bullets?", p: "uai ar ui ol-ueis estak...", s: "Tus balas" },
                        { e: "A bullet?", p: "a bulet", s: "Bala" },
                        { e: "Just stop your crying, it's a sign of the times", p: "yost estop...", s: "Señal" },
                        { e: "We gotta get away from here", p: "ui gara guet a-uei...", s: "Hay que irse" },
                        { e: "We gotta get away from here", p: "ui gara guet a-uei...", s: "Irnos de aquí" },
                        { e: "Just stop your crying, it'll be alright", p: "yost estop...", s: "Todo bien" },
                        { e: "They told me that the end is near", p: "de dei told mi...", s: "Fin cerca" },
                        { e: "We gotta get away from here", p: "ui gara guet...", s: "Irnos" },
                        { e: "Just stop your crying, have the time of your life", p: "yost estop...", s: "Pásalo increíble" },
                        { e: "Breaking through the atmosphere", p: "breikin thru...", s: "Atravesando atmósfera" },
                        { e: "And things are pretty good from here", p: "an dins ar priti gud...", s: "Todo bien" },
                        { e: "Remember everything will be alright", p: "rimember evridin...", s: "Todo bien" },
                        { e: "We can meet again somewhere", p: "ui kan mit aguen sam-uer", s: "Nos veremos" },
                        { e: "Somewhere far away from here", p: "sam-uer far a-uei...", s: "Lejos" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "No aprendemos" },
                        { e: "Why are we always stuck and running from the bullets?", p: "uai ar ui ol-ueis estak...", s: "¿Por qué huimos?" },
                        { e: "The bullets?", p: "de bulets", s: "Balas" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "Ya estuvimos" },
                        { e: "Why are we always stuck and running from the bullets?", p: "uai ar ui ol-ueis estak...", s: "¿Huimos?" },
                        { e: "The bullets?", p: "de bulets", s: "Balas" },
                        { e: "Just stop your crying, it's a sign of the times", p: "yost estop...", s: "Señal" },
                        { e: "We gotta get away from here", p: "ui gara guet a-uei...", s: "Irnos" },
                        { e: "We gotta get away from here", p: "ui gara guet a-uei...", s: "Irnos" },
                        { e: "Stop your crying, baby, it'll be alright", p: "estop iur krain, beibi...", s: "Todo bien nena" },
                        { e: "They told me that the end is near", p: "de dei told mi...", s: "Fin cerca" },
                        { e: "We gotta get away from here", p: "ui gara guet a-uei...", s: "Irnos" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "No aprendemos" },
                        { e: "Why are we always stuck and running from your bullets?", p: "uai ar ui ol-ueis estak...", s: "Tus balas" },
                        { e: "The bullets?", p: "de bulets", s: "Balas" },
                        { e: "We never learn, we've been here before", p: "ui never lern...", s: "No aprendemos" },
                        { e: "Why are we always stuck and running from your bullets?", p: "uai ar ui ol-ueis estak...", s: "Tus balas" },
                        { e: "Your bullets?", p: "iur bulets", s: "Balas" },
                        { e: "We don't talk enough", p: "ui dont tok i-naf", s: "No hablamos" },
                        { e: "We should open up", p: "ui shud oupen ap", s: "Abrirse" },
                        { e: "Before it's all too much", p: "bifor its ol tu mach", s: "Demasiado" },
                        { e: "Will we ever learn?", p: "uil ui ever lern", s: "¿Aprenderemos?" },
                        { e: "We've been here before", p: "uiv bin jiar bifor", s: "Ya estuvimos" },
                        { e: "It's just what we know", p: "its yost uat ui nou", s: "Sabemos esto" },
                        { e: "Stop your crying, baby, it's a sign of the times", p: "estop iur krain...", s: "Señal" },
                        { e: "We gotta get away (5x)", p: "ui gara guet a-uei", s: "Irse" },
                        { e: "We got to, we got to run (3x)", p: "ui gat tu ran", s: "Correr" },
                        { e: "We got to, we got to run away", p: "ui gat tu ran a-uei", s: "Huir" }
                    ]
                }
            ]
        }
    ],
    reactions: [
        { e: "Damn!", p: "dam!", s: "¡Rayos! / ¡Wow!" },
        { e: "Hell yeah!", p: "jel ié!", s: "¡Claro que sí!" },
        { e: "What the hell?", p: "uat de jel?", s: "¿Qué demonios?" },
        { e: "Damnit!", p: "dam-nit!", s: "¡Maldita sea!" },
        { e: "No hell way!", p: "nou jel uei!", s: "¡De ninguna manera!" },
        { e: "For sure, for sure", p: "for shur, for shur", s: "Totalmente" },
        { e: "Facts!", p: "fakts!", s: "¡Exacto!" },
        { e: "Goddamn!", p: "gad-dam!", s: "¡Maldición!" },
        { e: "What’s good?", p: "uats gud?", s: "¿Quieres pelea?" },
        { e: "Pull up!", p: "pul ap!", s: "¡Ven aquí! (Desafío)" },
        { e: "Square up!", p: "eskuer ap!", s: "¡Ponte en guardia!" },
        { e: "Keep that same energy!", p: "kip dat seim éneryi!", s: "¡Mantén esa actitud!" },
        { e: "Try me!", p: "trai mi!", s: "¡Atrevete!" },
        { e: "You’re food.", p: "iur fud.", s: "Eres presa fácil" },
        { e: "Don’t play with me!", p: "dont plei uid mi!", s: "¡No juegues conmigo!" },
        { e: "You want smoke?", p: "yu uant esmouk?", s: "¿Quieres problemas?" },
        { e: "Catch these hands!", p: "kach dis jands!", s: "¡Te voy a golpear!" },
        { e: "Run your pockets!", p: "ran iur pokets!", s: "¡Dame todo! (Robo)" },
        { e: "You’re a dub.", p: "iur a dab.", s: "Eres un fracaso" },
        { e: "You’re buggin’.", p: "iur baguin.", s: "Estás loco" },
        { e: "Get out of my face!", p: "guet aut ov mai feis!", s: "¡Quítate de mi vista!" },
        { e: "Stop cappin’!", p: "estop kapin!", s: "¡Deja de mentir!" },
        { e: "You’re reaching!", p: "iur richin!", s: "¡Estás inventando!" },
        { e: "Shut your trap!", p: "shat iur trap!", s: "¡Cierra el pico!" },
        { e: "Take a hike!", p: "teik a jaik!", s: "¡Lárgate!" },
        { e: "F outta here!", p: "ef aut-a jiar!", s: "¡Fuera de aquí!" },
        { e: "You’re a clown.", p: "iur a klaun.", s: "Eres un payaso" },
        { e: "Deadass, move!", p: "ded-as, muv!", s: "¡En serio, muévete!" },
        { e: "Go to hell!", p: "gou tu jel!", s: "¡Vete al infierno!" },
        { e: "Hell to pay!", p: "jel tu pei!", s: "Habrá consecuencias" },
        { e: "Burn in hell!", p: "bern in jel!", s: "¡Púdrete!" },
        { e: "To hell with you!", p: "tu jel uid yu!", s: "¡Al carajo contigo!" },
        { e: "Hell on earth.", p: "jel on erz.", s: "Infierno en la tierra" },
        { e: "Raising hell.", p: "reisin jel.", s: "Armar un escándalo" },
        { e: "Like a bat out of hell.", p: "laik a bat aut ov jel.", s: "A toda velocidad" },
        { e: "Hellish!", p: "jel-ish!", s: "¡Infernal!" },
        { e: "Worldstar!", p: "uorld-estar!", s: "¡Grito de pelea viral!" },
        { e: "He’s leaking!", p: "jis likin!", s: "Está sangrando" },
        { e: "He got rocked!", p: "ji gat rokt!", s: "Le dieron duro" },
        { e: "Knock his lights out!", p: "nok jis laits aut!", s: "¡Noquéalo!" },
        { e: "Oh, he’s done!", p: "ou, jis dan!", s: "¡Se acabó para él!" },
        { e: "He’s sleep!", p: "jis eslip!", s: "Quedó inconsciente" },
        { e: "Starch him!", p: "estarch jim!", s: "Déjalo tieso" },
        { e: "Body him!", p: "badi jim!", s: "Derrótalo totalmente" },
        { e: "He’s getting washed.", p: "jis guetin uash-d.", s: "Le están ganando fácil" },
        { e: "Folded him!", p: "foulded jim!", s: "Lo dobló del golpe" },
        { e: "Jesus H. Christ!", p: "yisus eish kraist!", s: "¡Jesucristo! (Enojo)" },
        { e: "Good God Almighty!", p: "gud gad ol-maiti!", s: "¡Dios Todopoderoso!" },
        { e: "Lord have mercy!", p: "lord jav mersi!", s: "¡Señor ten piedad!" },
        { e: "Sweet mother of God!", p: "suit mader ov gad!", s: "¡Santa madre de Dios!" },
        { e: "God as my witness!", p: "gad as mai uid-nes!", s: "¡Dios como mi testigo!" },
        { e: "For the love of God!", p: "for de lav ov gad!", s: "¡Por el amor de Dios!" },
        { e: "Holy mother!", p: "jouli mader!", s: "¡Santa madre!" },
        { e: "Heaven help us!", p: "jeven jelp as!", s: "¡Que el cielo nos ayude!" },
        { e: "Christ on a cracker!", p: "kraist on a kraker!", s: "¡Cristo bendito!" },
        { e: "God strike me down!", p: "gad estraik mi daun!", s: "¡Que Dios me fulmine!" }
    ],
    danger: [
        { e: "Watch out!", p: "uatch aut", s: "¡Cuidado!" },
        { e: "Heads up!", p: "jeds ap", s: "¡Ojo! / ¡Atención!" },
        { e: "Get down!", p: "guet daun", s: "¡Al suelo!" },
        { e: "Run!", p: "ran", s: "¡Corre!" },
        { e: "Duck!", p: "dak", s: "¡Agáchate!" },
        { e: "Freeze!", p: "friz", s: "¡Quieto!" },
        { e: "They're strapped", p: "deir estrap-t", s: "Están armados" },
        { e: "It's a setup", p: "its a set-ap", s: "Es una trampa" },
        { e: "Beat it!", p: "bit it", s: "¡Lárgate!" }
    ],
    money: [
        { e: "Get that bag", p: "guet dat bag", s: "Haz ese dinero" },
        { e: "I'm broke", p: "aim brouk", s: "No tengo dinero" },
        { e: "Bread / Dough", p: "bred / dou", s: "Dinero" },
        { e: "Hustle hard", p: "jas-el jard", s: "Esfuérzate al máximo" },
        { e: "Grind never stops", p: "graind never estops", s: "El esfuerzo no para" },
        { e: "Shady deal", p: "sheidi dil", s: "Negocio turbio" },
        { e: "A grand / A stack", p: "a grand / a estak", s: "Mil dólares" },
        { e: "Dirty money", p: "derti mani", s: "Dinero sucio" },
        { e: "Launder the money", p: "lon-der de mani", s: "Lavar dinero" }
    ],
    bodega: [
        { e: "Yo, Ock!", p: "yo, ok!", s: "¡Oye, amigo! (Al tendero)" },
        { e: "Lemme get a...", p: "lemi guet a", s: "Dame un..." },
        { e: "Deadass?", p: "ded-as?", s: "¿En serio? / ¿De verdad?" },
        { e: "Keep the change", p: "kip de cheinj", s: "Quédate con el cambio" },
        { e: "That's valid", p: "dats valid", s: "Eso es de calidad" },
        { e: "You buggin'!", p: "yu baguin!", s: "¡Estás loco!" }
    ],
    subway: [
        { e: "Watch the gap", p: "uatch de gap", s: "Cuidado con el hueco" },
        { e: "Step back from the doors", p: "estep bak fram de dors", s: "Aléjese de las puertas" },
        { e: "Uptown or Downtown?", p: "ap-taun or daun-taun?", s: "¿Hacia el norte o sur?" },
        { e: "The train is delayed", p: "de trein is di-leid", s: "El tren está retrasado" },
        { e: "Excuse me, lemme past", p: "exkius mi, lemi past", s: "Permiso, déjeme pasar" }
    ],
    slang: [
        { e: "Alright", p: "ol-rait", s: "Todo bien" },
        { e: "Body him", p: "badi jim", s: "Derrótalo" },
        { e: "Buggin'", p: "baguin", s: "Estar loco" },
        { e: "Deadass", p: "ded-as", s: "En serio / Verdad" },
        { e: "Facts", p: "fakts", s: "Es la verdad" },
        { e: "Hustle", p: "jas-el", s: "Buscavidas / Trabajo" },
        { e: "No Cap", p: "nou kap", s: "Sin mentiras" },
        { e: "Valid", p: "valid", s: "Bueno" },
        { e: "Yo!", p: "yo!", s: "Oye / Hola" },
        { e: "Concrete", p: "kon-krit", s: "Hormigón" },
        { e: "Empire", p: "em-pai-ar", s: "Imperio" },
        { e: "Meltin pot", p: "meltin pot", s: "Mezcla de culturas" },
        { e: "Stray", p: "estrei", s: "Vagar" },
        { e: "Vagabond", p: "va-ga-bond", s: "Vagabundo" },
        { e: "Atmosphere", p: "atmos-fiar", s: "Atmósfera" },
        { e: "Amusing", p: "amiusing", s: "Divertido" },
        { e: "Bullets", p: "bulets", s: "Balas" },
        { e: "Bribe", p: "braib", s: "Sobornar" },
        { e: "Brick", p: "brik", s: "Mucho frío" },
        { e: "Curfew", p: "kerfiu", s: "Toque de queda" },
        { e: "Delayed", p: "di-leid", s: "Retrasado" },
        { e: "Exemption", p: "eksempshon", s: "Excepción" },
        { e: "Fridge", p: "fridsh", s: "Nevera" },
        { e: "Gap", p: "gap", s: "Hueco" },
        { e: "Highway", p: "jai-uei", s: "Autopista" },
        { e: "Inspire", p: "inspai-ar", s: "Inspirar" },
        { e: "Jungle", p: "jan-guel", s: "Jungla" },
        { e: "Leaking", p: "likin", s: "Sangrando" },
        { e: "Maniac", p: "meiniak", s: "Maníaco" },
        { e: "Ock", p: "ok", s: "Amigo local" },
        { e: "Pull up", p: "pul ap", s: "Llegar" },
        { e: "Regrets", p: "rigrets", s: "Arrepentimientos" },
        { e: "Rocked", p: "rokt", s: "Noqueado" },
        { e: "Sirens", p: "sairens", s: "Sirenas" },
        { e: "Smoke", p: "esmouk", s: "Pelea / Humo" },
        { e: "Square up", p: "eskuer ap", s: "Pelear" },
        { e: "Trap", p: "trap", s: "Boca" },
        { e: "Uptown", p: "ap-taun", s: "Norte" },
        { e: "Washed", p: "uash-d", s: "Derrótado" },
        { e: "Broke", p: "brouk", s: "Sin dinero" },
        { e: "Bread", p: "bred", s: "Dinero" },
        { e: "Dough", p: "dou", s: "Dinero" },
        { e: "Grand", p: "grand", s: "Mil dólares" },
        { e: "Stack", p: "estak", s: "Fajo de billetes" },
        { e: "Shady", p: "sheidi", s: "Turbio" },
        { e: "Freeze", p: "friz", s: "Congelado / Quieto" },
        { e: "Duck", p: "dak", s: "Agacharse" },
        { e: "Strapped", p: "estrap-t", s: "Armado" },
        { e: "Setup", p: "set-ap", s: "Trampa" },
        { e: "Beat it", p: "bit it", s: "Lárgate" },
        { e: "Scram", p: "eskram", s: "Fuera" },
        { e: "Worldstar", p: "uorld-estar", s: "Pelea viral" },
        { e: "Leaking", p: "likin", s: "Sangrando" },
        { e: "Rocked", p: "rokt", s: "Duro golpe" },
        { e: "Folded", p: "foulded", s: "Doblado" },
        { e: "Mercy", p: "mersi", s: "Piedad" },
        { e: "Witness", p: "uid-nes", s: "Testigo" },
        { e: "Almighty", p: "ol-maiti", s: "Todopoderoso" },
        { e: "Cracker", p: "kraker", s: "Galleta / Pobre" },
        { e: "Strike", p: "estraik", s: "Golpear / Castigar" }
    ]
};